bot:
  name: ArsoBetonBot
  token: 6169399040:AAGAcK7IsBC9HBK1JYKXHMwwsrVZSeZrTFA

spring:
  datasource:
    username: root
    password: PassSQL1286
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&allowPublicKeyRetrieval=true

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect